### PR TITLE
Add portuguese

### PR DESCRIPTION
**Pull request by abarichello**

### CODE REVIEW

**Comment by abarichello** [comment]
Just tested and everything looks ok:
image
image
image

**Comment by jobtalle** [comment]
Thanks! How can I credit you in the readme.md?

**Comment by aBARICHELLO** [comment]
> Thanks! How can I credit you in the readme.md?

@abarichello is fine

**Comment by abarichello** [comment]
> Thanks! How can I credit you in the readme.md?

'Artur Barichello' is fine 👍🏼

**Pull request merged**
